import AppKit

// Types that signal sensitive or transient content — never stored.
// Password managers (1Password, LastPass, etc.) mark their clipboard writes
// with org.nspasteboard.ConcealedType so we can skip them silently.
private let blockedTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.agilebits.onepassword",
    "com.lastpass.lastpass",
    "com.bitwarden.desktop",
]

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int

    var onNewClip: ((String) -> Void)?

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.check()
        }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = pb.types ?? []
        let isBlocked = types.contains { blockedTypes.contains($0.rawValue) }
        guard !isBlocked else { return }

        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        onNewClip?(text)
    }
}
