import Foundation
import AppKit
import CmdCHistoryCore

// MARK: - Minimal test harness

private var passed = 0
private var failed = 0
private var currentSuite = ""

func suite(_ name: String, _ block: () -> Void) {
    currentSuite = name
    print("\n\(name)")
    block()
}

func test(_ name: String, _ block: () throws -> Void) {
    do {
        try block()
        print("  ✓ \(name)")
        passed += 1
    } catch {
        print("  ✗ \(name)")
        print("    → \(error)")
        failed += 1
    }
}

struct Fail: Error, CustomStringConvertible {
    let description: String
}

func expect<T: Equatable>(_ a: T, equals b: T, _ msg: String = "") throws {
    guard a == b else {
        throw Fail(description: msg.isEmpty ? "\(a) != \(b)" : msg)
    }
}

func expectTrue(_ value: Bool, _ msg: String = "expected true") throws {
    guard value else { throw Fail(description: msg) }
}

func expectFalse(_ value: Bool, _ msg: String = "expected false") throws {
    guard !value else { throw Fail(description: msg) }
}

// MARK: - ClipboardStore tests

func makeStore() -> (ClipboardStore, UserDefaults) {
    let suite = "CmdCHistoryTests-\(UUID().uuidString)"
    let defaults = UserDefaults(suiteName: suite)!
    return (ClipboardStore(defaults: defaults), defaults)
}

suite("ClipboardStore") {
    test("starts empty") {
        let (store, _) = makeStore()
        try expectTrue(store.all.isEmpty)
    }

    test("add single clip") {
        let (store, _) = makeStore()
        store.add("hello")
        try expect(store.all, equals: ["hello"])
    }

    test("newest clip is first") {
        let (store, _) = makeStore()
        store.add("first")
        store.add("second")
        try expect(store.all.first, equals: "second")
    }

    test("adding duplicate moves it to front") {
        let (store, _) = makeStore()
        store.add("a")
        store.add("b")
        store.add("a")
        try expect(store.all, equals: ["a", "b"])
    }

    test("cap drops oldest when limit exceeded") {
        let defaults = UserDefaults(suiteName: "cap-test-\(UUID().uuidString)")!
        let store = ClipboardStore(defaults: defaults, maxClips: 3)
        ["one", "two", "three", "four"].forEach { store.add($0) }
        try expect(store.all, equals: ["four", "three", "two"])
        try expectFalse(store.all.contains("one"), "oldest should be dropped")
    }

    test("exactly at cap does not drop anything") {
        let defaults = UserDefaults(suiteName: "cap-exact-\(UUID().uuidString)")!
        let store = ClipboardStore(defaults: defaults, maxClips: 3)
        ["a", "b", "c"].forEach { store.add($0) }
        try expect(store.all.count, equals: 3)
    }

    test("clear empties history") {
        let (store, _) = makeStore()
        store.add("hello")
        store.add("world")
        store.clear()
        try expectTrue(store.all.isEmpty)
    }

    test("persists across instances with same UserDefaults") {
        let (store, defaults) = makeStore()
        store.add("persisted")
        let store2 = ClipboardStore(defaults: defaults)
        try expect(store2.all, equals: ["persisted"])
    }

    test("correct order after multiple adds") {
        let (store, _) = makeStore()
        ["c", "b", "a"].forEach { store.add($0) }
        try expect(store.all, equals: ["a", "b", "c"])
    }

    test("clear then add works correctly") {
        let (store, _) = makeStore()
        store.add("old")
        store.clear()
        store.add("new")
        try expect(store.all, equals: ["new"])
    }
}

// MARK: - ClipboardMonitor blocked-type tests

suite("ClipboardMonitor — blocked types") {
    test("ConcealedType is blocked") {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("TransientType is blocked") {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.TransientType")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("AutoGeneratedType is blocked") {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("1Password type is blocked") {
        let types = [NSPasteboard.PasteboardType("com.agilebits.onepassword")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("LastPass type is blocked") {
        let types = [NSPasteboard.PasteboardType("com.lastpass.lastpass")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("Bitwarden type is blocked") {
        let types = [NSPasteboard.PasteboardType("com.bitwarden.desktop")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("Peter Maurer transient type is blocked") {
        let types = [NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("plain string type is not blocked") {
        let types = [NSPasteboard.PasteboardType.string]
        try expectFalse(ClipboardMonitor.isSensitive(types))
    }

    test("empty type list is not blocked") {
        try expectFalse(ClipboardMonitor.isSensitive([]))
    }

    test("mixed types with one blocked entry is blocked") {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        ]
        try expectTrue(ClipboardMonitor.isSensitive(types))
    }

    test("unknown type is not blocked") {
        let types = [NSPasteboard.PasteboardType("com.example.sometype")]
        try expectFalse(ClipboardMonitor.isSensitive(types))
    }
}

// MARK: - Summary

let total = passed + failed
print("\n\(total) tests — \(passed) passed, \(failed) failed")
if failed > 0 { exit(1) }
