import XCTest
import AppKit
@testable import CmdCHistoryCore

final class ClipboardMonitorTests: XCTestCase {

    // MARK: - Blocked type detection

    func testConcealedTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testTransientTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.TransientType")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testAutoGeneratedTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testOnePasswordTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("com.agilebits.onepassword")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testLastPassTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("com.lastpass.lastpass")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testBitwardenTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("com.bitwarden.desktop")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testPeterMaurerTransientTypeIsBlocked() {
        let types = [NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testPlainStringTypeIsNotBlocked() {
        let types = [NSPasteboard.PasteboardType.string]
        XCTAssertFalse(ClipboardMonitor.isSensitive(types))
    }

    func testEmptyTypesIsNotBlocked() {
        XCTAssertFalse(ClipboardMonitor.isSensitive([]))
    }

    func testMixedTypesWithBlockedOneIsBlocked() {
        let types = [
            NSPasteboard.PasteboardType.string,
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        ]
        XCTAssertTrue(ClipboardMonitor.isSensitive(types))
    }

    func testUnknownTypeIsNotBlocked() {
        let types = [NSPasteboard.PasteboardType("com.example.sometype")]
        XCTAssertFalse(ClipboardMonitor.isSensitive(types))
    }
}
